add entity bock
wolox-training/fpa-java pull request #5
Opened 2021-02-11 21:53 UTC by pachecowolox

## Summary
- add properties entityScan in TrainingApplication
- change property value spring.datasource.url
## Trello Card
- https://trello.com/c/Hiu0adGP/14-crear-modelo-de-book

2021-02-11 22:00 UTC, juanwongramirez approved these changes, later dismissed
Great!!

2021-02-12 14:20 UTC, marcegl91 requested changes

2021-02-12 14:20 UTC, marcegl91 commented on src/main/java/wolox/training/TrainingApplication.java
> +@EntityScan("wolox.training.models")
Why do you need this annotation?

2021-02-12 14:20 UTC, marcegl91 commented on src/main/java/wolox/training/models/Book.java
> +	@Column(nullable = false)
According to the card specification, genre can be nullable. The other fields should not be nullable, but this one can be set to null.

2021-02-12 14:20 UTC, marcegl91 commented on src/main/java/wolox/training/models/Book.java
> +	private Integer isbn;
ISBN should be a String, not an Integer.

2021-02-12 15:20 UTC, marcegl91 approved these changes

2021-02-12 15:21 UTC, juanwongramirez approved these changes

2021-02-12 15:21 UTC, merged