add Javadoc in controller the Book
wolox-training/fpa-java pull request #8
Opened 2021-02-15 19:40 UTC by pachecowolox

## Summary
- Add javadoc in BookController
## Trello Card
https://trello.com/c/qOEdirZQ/47-javadoc

2021-02-16 14:27 UTC, juanwongramirez requested changes

2021-02-16 14:27 UTC, juanwongramirez commented on src/main/java/wolox/training/controllers/BookController.java
> +	 * @return Object Book
You can use {@link Book} to reference the Book object

2021-02-16 18:57 UTC, juanwongramirez approved these changes

2021-02-17 14:08 UTC, marcegl91 approved these changes

2021-02-17 14:22 UTC, merged